import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Signal } from '../core/signal.js';
import type { CopyCheck, EditorCall, FiledReport } from '../pipeline/contracts.js';
import type { AgentEvent, AgentJob, AgentProvider, Detection } from './types.js';

/**
 * A deterministic, offline provider used for tests and demos. Spends no tokens,
 * needs no CLI, and produces role-appropriate output in the canonical contract
 * shapes so the whole pipeline can run headless. Output is derived from the job's
 * materials (a `signals.json` in the working dir, if present) so it cites real ids.
 */
export const fakeProvider: AgentProvider = {
  id: 'fake',
  displayName: 'Fake (offline test provider)',
  capabilities: {
    webSearch: false,
    fileAccess: true,
    jsonOutput: true,
    streaming: true,
    models: ['fake-1'],
  },
  async detect(): Promise<Detection> {
    return { installed: true, authenticated: true, version: 'fake-1', detail: 'Always available.' };
  },
  async *run(job: AgentJob): AsyncIterable<AgentEvent> {
    yield { type: 'start', provider: 'fake', model: job.model ?? 'fake-1' };
    const signals = readSignals(job.workingDir);
    const output = render(job, signals);
    // Emit the body in a couple of chunks so streaming consumers are exercised.
    const mid = Math.floor(output.length / 2);
    yield { type: 'text', text: output.slice(0, mid) };
    yield { type: 'text', text: output.slice(mid) };
    yield { type: 'usage', inputTokens: job.userPrompt.length, outputTokens: output.length };
    yield { type: 'done', output };
  },
};

function readSignals(workingDir: string): Signal[] {
  try {
    const raw = readFileSync(join(workingDir, 'signals.json'), 'utf8');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as Signal[]) : [];
  } catch {
    return [];
  }
}

function render(job: AgentJob, signals: Signal[]): string {
  switch (job.role) {
    case 'reporter':
      return JSON.stringify(fakeReport(signals), null, 2);
    case 'editor':
      return JSON.stringify(fakeCall(signals), null, 2);
    case 'copydesk':
      return JSON.stringify(fakeCheck(signals), null, 2);
    case 'writer':
      return fakeCopy(signals);
    default:
      return 'Fake provider: nothing to say.';
  }
}

function fakeReport(signals: Signal[]): FiledReport {
  const cited = signals.slice(0, 3);
  return {
    reporter: 'The Fake Desk',
    summary:
      cited.length > 0
        ? `Reviewed ${signals.length} signal(s). Lead item: "${cited[0]?.title}".`
        : 'No fresh signals on this beat.',
    facts: cited.map((s) => ({ claim: `Observed: ${s.title}`, signalId: s.id })),
    proposedAngle:
      cited.length > 0
        ? `Run "${cited[0]?.title}" as the day's development on this beat.`
        : 'Nothing to report; hold the space.',
    confidence: cited.length > 0 ? 0.7 : 0.2,
    urgency: 0.1,
    notes: 'Generated by the fake provider — no tokens spent.',
  };
}

function fakeCall(signals: Signal[]): EditorCall {
  const lead = signals[0];
  return {
    headline: lead ? titleCase(lead.title).slice(0, 80) : 'A Quiet Day On The Wire',
    standfirst: lead
      ? `What the ${lead.sourceType} beat turned up, and why it matters.`
      : 'The desks filed nothing worth the front page.',
    chosenAngle: lead ? `Lead with "${lead.title}".` : 'Hold the page.',
    placement: lead ? 'page_one' : 'brief',
    competingTakes: false,
    rationale: 'Fake editor: chose the freshest signal as the lead. Deterministic call.',
  };
}

function fakeCheck(signals: Signal[]): CopyCheck {
  const ids = new Set(signals.map((s) => s.id));
  return {
    pass: true,
    verifiedClaims: signals.slice(0, 3).map((s) => ({
      claim: `Observed: ${s.title}`,
      signalId: s.id,
      supported: ids.has(s.id),
    })),
    corrections: [],
    injectionFlags: [],
  };
}

function fakeCopy(signals: Signal[]): string {
  const lead = signals[0];
  if (!lead) return 'The wire was quiet. Nothing to print on this beat today.';
  const lines = [
    `${titleCase(lead.title)}`,
    '',
    `The desk reports fresh activity on the ${lead.sourceType} beat. ${lead.body.slice(0, 200)}`,
    '',
    ...signals.slice(1, 4).map((s) => `Also noted: ${s.title}. [${s.id}]`),
    '',
    `Source: [${lead.id}]${lead.url ? ` — ${lead.url}` : ''}`,
  ];
  return lines.join('\n');
}

function titleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}
