import { join } from 'node:path';

/**
 * An edition id or a story slug is about to become a directory name under the newsroom.
 * Both are generated by this program (`<date>-NNN` and `slugify()`), but they also arrive
 * over IPC from the interface and from the command line, so they are checked here, at the
 * one place every path is built, rather than trusted at each call site. Anything with a
 * separator, a dot or a leading dash is refused: `../` would otherwise walk out of the
 * editions folder and into whatever the caller then opens, deletes or overwrites.
 */
const SAFE_ID = /^[a-z0-9][a-z0-9_-]{0,119}$/i;
export function assertSafeId(id: string, what = 'id'): string {
  if (typeof id !== 'string' || !SAFE_ID.test(id)) {
    throw new Error(`Not a valid ${what}: ${JSON.stringify(id)}`);
  }
  return id;
}

/**
 * Canonical on-disk layout for a newsroom. Everything is a plain file the user can
 * open, grep, back up and commit. See docs/build-plan.md §9.3.
 */
export function paths(root: string) {
  const newsroom = join(root, 'newsroom');
  return {
    root,
    newsroom,
    configFile: join(newsroom, 'config.yaml'),
    staffFile: join(newsroom, 'staff.yaml'),
    styleFile: join(newsroom, 'style.md'),
    beatsDir: join(newsroom, 'beats'),
    personasDir: join(newsroom, 'staff'),
    /** Standing assignments the newsroom works on a cadence. */
    assignmentsDir: join(newsroom, 'assignments'),
    /** Per-assignment run state (last run, count), kept out of the editable config. */
    assignmentStateDir: join(root, 'wire', '.assignments'),
    /** Raw signals, before anyone has looked at them. */
    wireDir: join(root, 'wire'),
    /** Persistent adapter "seen" state, one JSON file per source. */
    stateDir: join(root, 'wire', '.state'),
    editionsDir: join(root, 'editions'),
    /** Directory for a specific edition. */
    editionDir(editionId: string) {
      return join(root, 'editions', assertSafeId(editionId, 'edition id'));
    },
    storyDir(editionId: string, slug: string) {
      return join(
        root,
        'editions',
        assertSafeId(editionId, 'edition id'),
        'stories',
        assertSafeId(slug, 'story slug'),
      );
    },
  };
}

export type NewsroomPaths = ReturnType<typeof paths>;
